### ISSUE TITLE
Incorrect timings in groupby 50 GB charts

### ISSUE THREAD

**Issue by tsghtst** [duckdblabs/db-benchmark#10]
Data in this [chart](https://duckdblabs.github.io/db-benchmark/groupby/G1_1e9_1e2_0_0_basic.png) (groupby 50 GB) is incorrect. Timings for each question seem way too small (smaller that for 5 GB) and do not add up to the timing at the top of the chart. E.g. DuckDB top timing is 143s, but for each question timings are less than 0.5s.

**Comment by Tmonster** [comment]
Timings for each query are by the minute in the chart linked. So a timing of 0.01 is 0.6 seconds. 

The reported results in the chart represent the addition of all query timings of a system to complete both query runs for all 5 queries.

**Comment by tsghtst** [comment]
My bad, didn't notice x axis units are minutes. However, a bit confusing as top chart units are seconds, but lower chart units are minutes.
