### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gitboy16** [duckdblabs/db-benchmark#19]
Hi,
I wanted to know how often will the benchmark be updated?
Just curious to know how some new solutions are performing.
Thank you

**Comment by Tmonster** [comment]
Hi gitboy16, We don't plan on running the benchmarks too often. Currently the next planned benchmark run will take place after the duckdb 0.9 release, which should happen around September

**Comment by Tmonster** [comment]
@gitboy16  
new results are up!
https://duckdblabs.github.io/db-benchmark/

Heads up that we changed to a new machine to test. You can read more about it here https://duckdb.org/2023/11/03/db-benchmark-update.html

let me know if you have any questions, the whole benchmarking process has been changed so others can run the benchmark, report results, and get the benchmark updated
