### ISSUE TITLE
Publish DataFusion to report

### ISSUE THREAD

**Issue by Dandandan** [duckdblabs/db-benchmark#23]

**Comment by Tmonster** [comment]
Hi Daniël, I plan on running the benchmark again during the next duckdb release, which should be sometime in September. DataFusion results will be included then!

**Comment by MrPowers** [comment]
@Tmonster - do you know when the updated results will be published?  Thanks!

**Comment by Tmonster** [comment]
Hi @MrPowers should be sometime in the next couple of days!. Some of the 50GB join runs weren't getting logged for some reason, so I had to spend some time debugging them

**Comment by MrPowers** [comment]
Awesome @Tmonster, thanks for the great work on this project!!

**Comment by MrPowers** [comment]
@Tmonster - just following up here.  Thank you!

**Comment by Tmonster** [comment]
@MrPowers Results will be published Friday with a blog post. Stay tuned! 👍

**Comment by MrPowers** [comment]
@Tmonster - awesome, thanks!!

**Comment by Dandandan** [comment]
@Tmonster awesome!

**Comment by Tmonster** [comment]
new results are up! Heads up that we changed to a new machine to test. You can read more about it here https://duckdb.org/2023/11/03/db-benchmark-update.html

**Comment by Tmonster** [comment]
Hi @Dandandan can this be closed now that datafusion results have been published?

**Comment by Dandandan** [comment]
Yeah, thank you @Tmonster for the effort :)
