### ISSUE TITLE
duckdb-latest fails

### ISSUE THREAD

**Issue by quasiben** [duckdblabs/db-benchmark#39]
When trying to setup duckdb-latest I get an error:

```bash
~/db-benchmark$ bash duckdb-latest/setup-duckdb-latest.sh
Downloading GitHub repo duckdb/duckdb@HEAD
Error: Failed to install 'duckdb' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
Execution halted
```

The [docs page](https://duckdb.org/docs/installation/) recommends doing the following:

> install.packages('duckdb', repos=c('https://duckdb.r-universe.dev', 'https://cloud.r-project.org'))

I'm probably doing something wrong as I'm not very familiar with R

**Comment by jangorecki** [comment]
Try run commands from the script one by one a see which one fails. According to best practices packages should be installed from tar.gz file rather than a directory, as it is now in the script.

**Comment by quasiben** [comment]
Thanks for the quick response @jangorecki .

The [Rscript install line](https://github.com/duckdblabs/db-benchmark/blob/00c4fdd2625f64caf6e63844678fe5f3ec546af9/duckdb-latest/setup-duckdb-latest.sh#L8C1-L8C76) fails:

```bash
$/db-benchmark$ Rscript -e 'install.packages("DBI", lib="./duckdb-latest/r-duckdb-latest")'
Error in contrib.url(repos, type) :
  trying to use CRAN without setting a mirror
Calls: install.packages -> startsWith -> contrib.url
Execution halted
```

**Comment by jangorecki** [comment]
Add `repos="https://cloud.r-project.org"` to install.packages call

**Comment by quasiben** [comment]
Thanks!  That's moving things along nicely now.  If it succeeds should I file a PR to update the script ?

**Comment by jangorecki** [comment]
user, or an org, may have local cran mirror, then hardcoding those may not be ideal, but most commonly it won't be a problem anyway, so I would say go ahead

**Comment by Tmonster** [comment]
Hi @quasiben are you still experiencing this issue or can I close it?

**Comment by quasiben** [comment]
Yup yup, thanks for closing and thank you to @jangorecki for helping me resolve the issue
