### ISSUE TITLE
Add cuDF

### ISSUE THREAD

**Issue by jmakov** [duckdblabs/db-benchmark#63]
Any particular reason why cuDF is left out especially since it's included in the original repo?

**Comment by Tmonster** [comment]
Two reasons,
1. Including libraries that use separate hardware is not a good way to compare the performance of software libraries. We would like to maintain hardware parity across the solutinos.
2. Maintaining the GPU accelerated solutions is also not something I am keen to do.

If cuDF can run exclusively on CPUs then I will happily include it again if you provide a PR to fix any current problems

**Comment by jmakov** [comment]
Thanks for the clarification. I guess from the user's perspective it would be interesting to see what's possible e.g. should you invest in a CPU with AVX512 or rather a GPU. I agree supporting a GPU env even with Docker requires a lot.

**Comment by rootsmusic** [comment]
cuDF performed a [Database-like ops benchmark](https://docs.rapids.ai/api/cudf/stable/cudf_pandas/benchmarks/) with a CPU and GPU for cudf.pandas.

**Comment by jangorecki** [comment]
> RAPIDS performed a [Database-like ops benchmark](https://docs.rapids.ai/api/cudf/stable/cudf_pandas/benchmarks/) with a CPU and GPU for cudf.pandas.

Thanks for link.
After looking closer the time there doesn't look very reliable. Both h2oai and duckdb run q10 groupby data.table in 12s (recent) and 17s (old), while cudf benchmark of data.table needs 34s for same operation. Don't know what can be the reason, machine spec, compiler, compilation flags?
