### ISSUE TITLE
Some values in the picture seems broken

### ISSUE THREAD

**Issue by eitsupi** [duckdblabs/db-benchmark#8]
Some values are showed as NA now.

![image](https://user-images.githubusercontent.com/50911393/233967143-03f867dc-cc80-4ed3-9736-2243cb2ac0d2.png)

**Comment by Tmonster** [comment]
Hi, 

Yes, thank you for noticing. I tracked down the bug, and published new results to include JuliaDF. The NA values should no longer be present

https://duckdblabs.github.io/db-benchmark/

**Comment by eitsupi** [comment]
Looks fine, thanks for quick updates!
